#!/bin/bash

set -ex

name=$1
ver=$2

if [ -z "$name" -o -z "$ver" ]; then
    echo "Usage: $0 [name] [version]"
    exit 1
fi

namever=${name}-${ver}

url=http://download.kde.org/stable/${name}/${namever}.tar.xz
#curl -LO $url
wget $url
tar -xJf ${namever}.tar.xz
cd ${namever}
mkdir build && cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DKDE_INSTALL_USE_QT_SYS_PATHS=OFF \
    -DKDE_INSTALL_LIBDIR=/usr/lib64 \
    -DKDE_INSTALL_SYSCONFDIR=/etc \
    -DKDE_INSTALL_QTPLUGINDIR=/usr/lib64/qt5/plugins \
    -DKDE_INSTALL_PLUGINDIR=/usr/lib64/qt5/plugins \
    -DKDE_INSTALL_QMLDIR=/usr/lib64/qml \
    -DKDE_INSTALL_QTQUICKIMPORTSDIR=/usr/lib64/qt5/imports \
    -DECM_MKSPECS_INSTALL_DIR=/usr/lib64/qt5/mkspecs/modules \
    -DKDE_INSTALL_METAINFODIR=/usr/share/metainfo \
    -DBUILD_TESTING=Off
cmake --build . -- -j $(getconf _NPROCESSORS_ONLN)
cmake --install .
