#!/bin/bash

set -ex

name=umockdev
ver=0.14.1

curl -LO https://github.com/martinpitt/${name}/releases/download/${ver}/${name}-${ver}.tar.xz
tar -xJf ${name}-${ver}.tar.xz
cd ${name}-${ver}
./configure --prefix=/usr --libdir=/usr/lib64 --disable-static --disable-gtk-doc
make -j $(getconf _NPROCESSORS_ONLN)
make install
