FROM fedora:rawhide

# Install packages
RUN dnf update -y && \
    dnf install -y sudo \
        gcc-c++ clang git cmake ninja-build extra-cmake-modules \
        qt6-qtbase-static qt6-qtbase-private-devel \
        qt6-qtbase-devel \
        qt6-qtserialport-devel \
        qt6-qtshadertools-devel \
        qt6-qttools-devel \
        qt6-qtdeclarative-devel \
        qt6-qtpdf-devel \
        qt6-qtpositioning-devel \
        qt6-qtwebchannel-devel \
        qt6-qtmultimedia-devel \
        qt6-qtspeech-devel \
        qt6-qtwebview-devel \
        qt6-qtwebengine-devel \
        qt6-qtwebsockets-devel \
        qt6-qtsensors-devel \
        qt6-qtremoteobjects-devel \
        qt6-qtnetworkauth-devel \
        qt6-qt3d-devel \
        qt6-qtcharts-devel \
        qt6-qtdatavis3d-devel \
        qt6-qtquick3d-devel \
        qt6-qtquicktimeline-devel \
        qt6-qtscxml-devel \
        qt6-qtvirtualkeyboard-devel \
        qt6-qtwayland-devel \
        qt6-qtconnectivity-devel \
        qt6-qtserialbus-devel \
        qt6-qt5compat-devel \
        qt6-qtbase-private-devel \
        qt6-qtlottie-devel \
        qt6-qtsvg-devel \
        wayland-devel wayland-protocols-devel \
        pam-devel \
        polkit-devel polkit-qt6-1-devel \
        kf6-solid-devel \
        systemd-devel libdrm-devel mesa-libgbm-devel libinput-devel \
        xcb-util-cursor-devel libXcursor-devel \
        pulseaudio-libs-devel \
        NetworkManager-libnm-devel ModemManager-glib-devel kf6-networkmanager-qt-devel kf6-modemmanager-qt-devel \
        glib2-devel dconf \
        pipewire-devel pipewire-utils \
        libxkbcommon-devel \
        flatpak-devel \
        appstream-qt-devel \
        umockdev-devel
