name: Build container image

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build image and publish to Docker Hub
      run: |
        echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin
        cd ${{ inputs.name }} && make DOCKER=docker build && make DOCKER=docker push
