name: Docker

on:
  schedule:
    - cron: '30 12 * * */7'
  repository_dispatch:
    types:
      - rebuild

jobs:
  build-suse-qt515:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build image and publish to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        cd suse-qt515 && make DOCKER=docker build && make DOCKER=docker push
