name: Docker

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: '30 12 * * *'
  repository_dispatch:
    types:
      - rebuild
  workflow_dispatch:

jobs:
  build-suse-qt515:
    uses: ./.github/workflows/build-image.yml
    with:
      name: suse-qt515
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
  build-suse-qt66:
    uses: ./.github/workflows/build-image.yml
    with:
      name: suse-qt66
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
  build-fedora:
    uses: ./.github/workflows/build-image.yml
    with:
      name: fedora
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
