name: Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 12 * * *'

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        image:
          - fedora-31
          - fedora-jenkins-31
          - suse-qt512
          - suse-qt514
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish to Docker Hub
      run: |
        if ./was-it-changed ${{ matrix.image }}; then
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          cd ${{ matrix.image }} && make DOCKER=docker build && make DOCKER=docker push
        fi
