name: Docker

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  schedule:
    - cron: '30 12 * * *'
  repository_dispatch:
    types:
      - rebuild
  workflow_dispatch:

jobs:
  build-image:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        name: [suse-qt515, suse-qt68, fedora]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build image and publish to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          cd ${{ matrix.name }} && make DOCKER=docker build && make DOCKER=docker push
