name: Docker

on:
  schedule:
    - cron: '30 12 * * */7'
  repository_dispatch:
    types:
      - rebuild

jobs:
  build-suse-qt515:
    uses: ./.github/workflows/build-image.yml
    with:
      name: suse-qt515
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
  build-suse-qt62:
    uses: ./.github/workflows/build-image.yml
    with:
      name: suse-qt64
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
